import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ko': {
'About': 'About',
'Text Builder': '문자공장',
'Input text here': '텍스트를 입력하세요',
'Copy': '복사',
'Clear': '삭제',
'Source text copied': '텍스트를 복사했습니다',
'Source text': '원본',
'Result text copied': '결과 텍스트를 복사했습니다',
'Text will be converted here': '텍스트가 여기에 변환됩니다',
'Result text': '결과',
'refer_to_the_usage_using_sample_text': '샘플 텍스트를 사용하여 사용법을 참조하십시오',
'todays_date_will_be_replaced_with_yyymmdd_eg_20210713': '오늘날짜의 YYYMMDD로 대체됩니다. 예. 20210713.',
'yesterdays_date_will_be_replaced_with_yyymmdd_eg_20210713': '어제날짜의 YYYYMMDD로 대체됩니다. 예. 20210713.',
'View Sample': '샘플보기',
'Convert to uppercase': '대문자로 변환합니다',
'Convert to lowercase': '소문자로 변환합니다',
'Convert grid to insert sql': '그리드를 INSERT SQL로 변환합니다',
'Replace keywords to value': 'KEYWORD를 VALUE로 치환합니다',
'years': '년',
'months': '개월',
'days': '일',
'Replace to d-days from given date to today': '주어진 날짜에서 오늘까지 D-Day로 바꿉니다(시작일포함)',
'Replace to d-days between two given date': '주어진 두 날짜 사이의 D-Day로 바꿉니다(시작일포함)',
'Replace to years-months-days from given date to today': '주어진 날짜부터 오늘까지 년 월 일로 바꿉니다',
'Replace to days from given date to today': '주어진 날짜에서 오늘까지 일수로 바꿉니다',
'Replace to days between two given date': '주어진 두 날짜 사이의 일수로 바꿉니다',
'Clear All': '전체삭제',
'Clear Line': '행삭제',
'Flutter App by EnooSoft': 'EnooSoft의 Flutter App입니다',
'Date and time now': '현재 날짜와 시간(yyyy-MM-dd hh:MM:ss)',
'Source text must be at least 2 lines': '원본텍스트는 최소 2줄이어야 합니다',
'Current Year (2 digits)': '현재 연도(2자리)',
'Current Month (2 digits)': '현재 월도(2자리)',
'Current Date (2 digits)': '현재 날짜(2자리)',
'Current Hour (24 Hours)': '현재 시간(24시간)',
'Current minutes': '현재 분',
'Current seconds': '현재 초',
'Keyword': '키워드',
'Filter': '필터',
'Select Keyword': '키워드 선택',
'Please select the keyword from the list': '리스트에서 키워드를 선택하세요',
'Cancel': '취소',
'Confirm': '확인',
'Select': '선택',
'play store app title': '문자공장 - 다양한 키워드와 필터로 메시지를 만듦니다',
'check this app detail': '"문자공장" 앱을 확인하세요',
'Share App': '앱공유',
'😊Have a nice day🎉 - EnooSoft': '😊좋은 하루 보내세요🎉 - EnooSoft',
'Text Builder - Keyword suggestion for this app': '문자공장 - 키워드를 제안합니다',
'Please make a "Keyword" that works like this': '이렇게 작동하는 "키워드"를 만들어주세요.',
'Keyword suggestion': '키워드 제안',
'Returns the date added the number': '오늘 날짜에 추가된 날짜를 반환합니다',
},
'en': {
'About': 'About',
'Text Builder': 'Text Builder',
'Input text here': 'Input text here',
'Copy': 'Copy',
'Clear': 'Clear',
'Source text copied': 'Source text copied',
'Source text': 'Source text',
'Result text copied': 'Result text copied',
'Text will be converted here': 'Text will be converted here',
'Result text': 'Result text',
'refer_to_the_usage_using_sample_text': 'Refer to the usage using sample text',
'todays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'Today\'s date will be replaced with yyyMMdd. eg. 20210713',
'yesterdays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'Yesterday\'s date will be replaced with yyyMMdd. eg. 20210713',
'View Sample': 'View Sample',
'Convert to uppercase': 'Convert to uppercase',
'Convert to lowercase': 'Convert to lowercase',
'Convert grid to insert sql': 'Convert grid to insert sql',
'Replace keywords to value': 'Replace keywords to value',
'years': 'years',
'months': 'months',
'days': 'days',
'Replace to d-days from given date to today': 'Replace to d-day from given date to today',
'Replace to d-days between two given date': 'Replace to days between two given date',
'Replace to years-months-days from given date to today': 'Replace to years-months-days from given date to today',
'Replace to days from given date to today': 'Replace to days from given date to today',
'Replace to days between two given date': 'Replace to days between two given date',
'Clear All': 'Clear All',
'Clear Line': 'Clear Line',
'Flutter App by EnooSoft': 'Flutter App by EnooSoft',
'Date and time now': 'Date and time now',
'Source text must be at least 2 lines': 'Source text must be at least 2 lines',
'Current Year (2 digits)': 'Current Year (2 digits)',
'Current Month (2 digits)': 'Current Month (2 digits)',
'Current Date (2 digits)': 'Current Date (2 digits)',
'Current Hour (24 Hours)': 'Current Hour (24 Hours)',
'Current minutes': 'Current minutes',
'Current seconds': 'Current seconds',
'Keyword': 'Keyword',
'Filter': 'Filter',
'Select Keyword': 'Select Keyword',
'Please select the keyword from the list': 'Please select the keyword from the list',
'Cancel': 'Cancel',
'Confirm': 'Confirm',
'Select': 'Select',
'play store app title': 'Text Builder - Create messages with various keywords and filters',
'check this app detail': 'Check this app : "Text Builder - Create messages with various keywords and filters',
'Share App': 'Share App',
'😊Have a nice day🎉 - EnooSoft': '😊Have a nice day🎉 - EnooSoft',
'Text Builder - Keyword suggestion for this app': 'Text Builder - Keyword suggestion for this app',
'Please make a "Keyword" that works like this': 'Please make a "Keyword" that works like this',
'Keyword suggestion': 'Keyword suggestion',
'Returns the date added the number': 'Returns the date added the number',
},
'fr': {
'About': 'À propos de',
'Text Builder': 'Constructeur de texte',
'Input text here': 'Texte d\'entrée ici',
'Copy': 'Copie',
'Clear': 'Dégager',
'Source text copied': 'Texte source copié',
'Source text': 'Texte source',
'Result text copied': 'Texte de résultat copié',
'Text will be converted here': 'Le texte sera converti ici',
'Result text': 'Texte de résultat',
'refer_to_the_usage_using_sample_text': 'Reportez-vous à l\'utilisation à l\'aide d\'un exemple de texte',
'todays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'La date d\'aujourd\'hui sera remplacée par YYYMMDD. par exemple. 20210713',
'yesterdays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'La date d\'hier sera remplacée par YYYMMDD. par exemple. 20210713',
'View Sample': 'Afficher un échantillon',
'Convert to uppercase': 'Convertir en majuscule',
'Convert to lowercase': 'Convertir en minuscule',
'Convert grid to insert sql': 'Convertir la grille pour insérer SQL',
'Replace keywords to value': 'Remplacer les mots-clés à la valeur',
'years': 'ans',
'months': 'mois',
'days': 'journées',
'Replace to d-days from given date to today': 'Remplacer au jour J par rapport à la date donnée à aujourd\'hui',
'Replace to d-days between two given date': 'Remplacer aux jours entre deux date donnée',
'Replace to years-months-days from given date to today': 'Remplacer à des années-mois-jours à compter de la date donnée à aujourd\'hui',
'Replace to days from given date to today': 'Remplacer aux jours de la date donnée à aujourd\'hui',
'Replace to days between two given date': 'Remplacer aux jours entre deux date donnée',
'Clear All': 'Tout effacer',
'Clear Line': 'Ligne claire',
'Flutter App by EnooSoft': 'Flutter app par Enoosoft',
'Date and time now': 'Date et heure maintenant',
'Source text must be at least 2 lines': 'Le texte source doit être d\'au moins 2 lignes',
'Current Year (2 digits)': 'Année en cours (2 chiffres)',
'Current Month (2 digits)': 'Mois en cours (2 chiffres)',
'Current Date (2 digits)': 'Date de courant (2 chiffres)',
'Current Hour (24 Hours)': 'Heure actuelle (24 heures)',
'Current minutes': 'Minutes actuelles',
'Current seconds': 'Secondes actuelles',
'Keyword': 'Mot-clé',
'Filter': 'Filtre',
'Select Keyword': 'Sélectionnez le mot-clé',
'Please select the keyword from the list': 'Veuillez sélectionner le mot-clé dans la liste.',
'Cancel': 'Annuler',
'Confirm': 'Confirmer',
'Select': 'Sélectionner',
'play store app title': 'Constructeur de texte - Créez des messages avec divers mots-clés et filtres',
'check this app detail': 'Cochez cette application: «Constructeur de texte - Créez des messages avec différents mots-clés et filtres',
'Share App': 'Partager l\'application',
'😊Have a nice day🎉 - EnooSoft': '😊Avoir une bonne journée🎉 - Enoosoft',
'Text Builder - Keyword suggestion for this app': 'Constructeur de texte - Suggestion de mots-clés pour cette application',
'Please make a "Keyword" that works like this': 'S\'il vous plaît faire un "mot-clé" qui fonctionne comme celui-ci',
'Keyword suggestion': 'Suggestion de mots-clés',
'Returns the date added the number': 'Retourne la date ajoutée le numéro',
},
'es': {
'About': 'Acerca de',
'Text Builder': 'Constructor de texto',
'Input text here': 'Texto de entrada aquí',
'Copy': 'Dupdo',
'Clear': 'Claro',
'Source text copied': 'Texto de origen copiado',
'Source text': 'Texto de origen',
'Result text copied': 'Texto de resultados copiado',
'Text will be converted here': 'El texto se convertirá aquí.',
'Result text': 'Texto de resultado',
'refer_to_the_usage_using_sample_text': 'Consulte el uso utilizando texto de muestra.',
'todays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'La fecha de hoy será reemplazada por YYYMMDD. p.ej. 20210713',
'yesterdays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'La fecha de ayer será reemplazada por YYYMMDD. p.ej. 20210713',
'View Sample': 'Ver muestra',
'Convert to uppercase': 'Convertir en mayúsculas',
'Convert to lowercase': 'Convertir a minúsculas',
'Convert grid to insert sql': 'Convertir cuadrícula para insertar SQL',
'Replace keywords to value': 'Reemplace las palabras clave para valorar',
'years': 'años',
'months': 'meses',
'days': 'dias',
'Replace to d-days from given date to today': 'Reemplace a D-Day desde la fecha dada hasta hoy',
'Replace to d-days between two given date': 'Reemplace a los días entre dos fechas dadas',
'Replace to years-months-days from given date to today': 'Reemplace a años, meses, días desde la fecha dada hasta hoy',
'Replace to days from given date to today': 'Reemplace a los días desde la fecha dada hasta hoy',
'Replace to days between two given date': 'Reemplace a los días entre dos fechas dadas',
'Clear All': 'Limpiar todo',
'Clear Line': 'Línea clara',
'Flutter App by EnooSoft': 'Aplicación de aleteo por EnOosoft',
'Date and time now': 'Fecha y hora ahora',
'Source text must be at least 2 lines': 'El texto de la fuente debe ser de al menos 2 líneas.',
'Current Year (2 digits)': 'Año actual (2 dígitos)',
'Current Month (2 digits)': 'Mes actual (2 dígitos)',
'Current Date (2 digits)': 'Fecha actual (2 dígitos)',
'Current Hour (24 Hours)': 'Hora actual (24 horas)',
'Current minutes': 'Minutos actuales',
'Current seconds': 'Segundos actuales',
'Keyword': 'Palabra clave',
'Filter': 'Filtrar',
'Select Keyword': 'Seleccione palabra clave',
'Please select the keyword from the list': 'Por favor, seleccione la palabra clave de la lista',
'Cancel': 'Cancelar',
'Confirm': 'Confirmar',
'Select': 'Seleccione',
'play store app title': 'Constructor de texto: cree mensajes con varias palabras clave y filtros',
'check this app detail': 'Verifique esta aplicación: "Constructor de texto: cree mensajes con varias palabras clave y filtros',
'Share App': 'Compartir aplicación',
'😊Have a nice day🎉 - EnooSoft': '😊Have un buen día🎉 - Enoosoft',
'Text Builder - Keyword suggestion for this app': 'Constructor de texto - Sugerencia de palabras clave para esta aplicación',
'Please make a "Keyword" that works like this': 'Por favor, haga una "palabra clave" que funcione de esta manera.',
'Keyword suggestion': 'Sugerencia de la palabra clave',
'Returns the date added the number': 'Devuelve la fecha agregada el número',
},
'de': {
'About': 'Über',
'Text Builder': 'Text Builder.',
'Input text here': 'Eingabestext hier.',
'Copy': 'Kopieren',
'Clear': 'Klar',
'Source text copied': 'Quelltext kopiert',
'Source text': 'Quellentext',
'Result text copied': 'Ergebnistext kopiert.',
'Text will be converted here': 'Der Text wird hier konvertiert',
'Result text': 'Ergebnistext',
'refer_to_the_usage_using_sample_text': 'Siehe Verwendung mit Beispieltext',
'todays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'Das heutige Datum wird durch yyymmdd ersetzt. z.B. 20210713.',
'yesterdays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'Das Datum von gestern wird durch YYYMMDD ersetzt. z.B. 20210713.',
'View Sample': 'Probe anzeigen.',
'Convert to uppercase': 'In Großbuchstaben umwandeln',
'Convert to lowercase': 'In Kleinbuchstaben umwandeln',
'Convert grid to insert sql': 'Konvertieren Sie das Raster, um SQL einzufügen',
'Replace keywords to value': 'Ersetzen Sie Schlüsselwörter, um den Wert zu erhalten',
'years': 'Jahre',
'months': 'Monate',
'days': 'Tage',
'Replace to d-days from given date to today': 'Ersetzen Sie den D-Day von einem bestimmten Datum bis heute',
'Replace to d-days between two given date': 'Ersetzen Sie bis Tage zwischen zwei Jahren',
'Replace to years-months-days from given date to today': 'Ersetzen Sie bis Jahre-Monate-Tage bis heute bis heute',
'Replace to days from given date to today': 'Ersetzen Sie bis Tage von einem bestimmten Datum bis heute',
'Replace to days between two given date': 'Ersetzen Sie bis Tage zwischen zwei Jahren',
'Clear All': 'Alles löschen',
'Clear Line': 'Klare Linie',
'Flutter App by EnooSoft': 'Flutter-App von ENOOSOFT',
'Date and time now': 'Datum und Uhrzeit jetzt',
'Source text must be at least 2 lines': 'Quelltext muss mindestens 2 Zeilen betragen',
'Current Year (2 digits)': 'Aktuelles Jahr (2 Ziffern)',
'Current Month (2 digits)': 'Aktueller Monat (2 Ziffern)',
'Current Date (2 digits)': 'Aktuelles Datum (2 Ziffern)',
'Current Hour (24 Hours)': 'Aktuelle Stunde (24 Stunden)',
'Current minutes': 'Aktuelle Minuten',
'Current seconds': 'Aktuelle Sekunden',
'Keyword': 'Stichwort',
'Filter': 'Filter',
'Select Keyword': 'Schlüsselwort auswählen.',
'Please select the keyword from the list': 'Bitte wählen Sie das Schlüsselwort aus der Liste aus',
'Cancel': 'Stornieren',
'Confirm': 'Bestätigen Sie',
'Select': 'Auswählen',
'play store app title': 'Text Builder - Erstellen Sie Nachrichten mit verschiedenen Keywords und Filtern',
'check this app detail': 'Überprüfen Sie diese App: "Text Builder - Meldungen erstellen mit verschiedenen Keywords und Filtern',
'Share App': 'App teilen',
'😊Have a nice day🎉 - EnooSoft': '😊Habe ein schöner Tag - Enoosoft',
'Text Builder - Keyword suggestion for this app': 'Text Builder - Schlüsselwortvorschlag für diese App',
'Please make a "Keyword" that works like this': 'Bitte machen Sie ein "Keyword", das so funktioniert',
'Keyword suggestion': 'Schlüsselwortvorschlag',
'Returns the date added the number': 'Gibt das Datum zurück, das die Nummer hinzugefügt hat',
},
'hi': {
'About': 'के बारे में',
'Text Builder': 'टेक्स्ट बिल्डर',
'Input text here': 'इनपुट पाठ यहाँ',
'Copy': 'प्रतिलिपि',
'Clear': 'स्पष्ट',
'Source text copied': 'स्रोत पाठ कॉपी किया गया',
'Source text': 'स्रोत इबारत',
'Result text copied': 'परिणाम पाठ कॉपी किया गया',
'Text will be converted here': 'पाठ यहाँ परिवर्तित किया जाएगा',
'Result text': 'परिणाम पाठ',
'refer_to_the_usage_using_sample_text': 'नमूना पाठ का उपयोग करके उपयोग का संदर्भ लें',
'todays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'आज की तारीख YYYMMDD के साथ बदल दी जाएगी। उदाहरण के लिए। 20210713',
'yesterdays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'कल की तारीख को YYYMMDD के साथ बदल दिया जाएगा। उदाहरण के लिए। 20210713',
'View Sample': 'नमूना देखें',
'Convert to uppercase': 'अपरकेस में कनवर्ट करें',
'Convert to lowercase': 'लोअरकेस में कनवर्ट करें',
'Convert grid to insert sql': 'SQL डालने के लिए ग्रिड कनवर्ट करें',
'Replace keywords to value': 'कीवर्ड को मूल्य में बदलें',
'years': 'वर्षों',
'months': 'महीने',
'days': 'दिन',
'Replace to d-days from given date to today': 'दी गई तारीख से आज तक डी-डे को बदलें',
'Replace to d-days between two given date': 'दो दी गई तारीख के बीच के दिनों में बदलें',
'Replace to years-months-days from given date to today': 'दी गई तारीख से साल-महीने-दिनों तक बदलें',
'Replace to days from given date to today': 'दी गई तारीख से आज तक बदलें',
'Replace to days between two given date': 'दो दी गई तारीख के बीच के दिनों में बदलें',
'Clear All': 'सभी साफ करें',
'Clear Line': 'स्पष्ट रेखा',
'Flutter App by EnooSoft': 'Enoosoft द्वारा Flutter App',
'Date and time now': 'दिनांक और समय',
'Source text must be at least 2 lines': 'स्रोत पाठ कम से कम 2 लाइनों का होना चाहिए',
'Current Year (2 digits)': 'चालू वर्ष (2 अंक)',
'Current Month (2 digits)': 'वर्तमान माह (2 अंक)',
'Current Date (2 digits)': 'वर्तमान दिनांक (2 अंक)',
'Current Hour (24 Hours)': 'वर्तमान घंटा (24 घंटे)',
'Current minutes': 'वर्तमान मिनट',
'Current seconds': 'वर्तमान सेकंड',
'Keyword': 'कीवर्ड',
'Filter': 'फ़िल्टर',
'Select Keyword': 'कीवर्ड का चयन करें',
'Please select the keyword from the list': 'कृपया सूची से कीवर्ड का चयन करें',
'Cancel': 'रद्द करना',
'Confirm': 'पुष्टि करें',
'Select': 'चुनते हैं',
'play store app title': 'टेक्स्ट बिल्डर - विभिन्न कीवर्ड और फ़िल्टर के साथ संदेश बनाएं',
'check this app detail': 'इस ऐप को देखें: "टेक्स्ट बिल्डर - विभिन्न कीवर्ड और फ़िल्टर के साथ संदेश बनाएं',
'Share App': 'ऐप शेयर करें',
'😊Have a nice day🎉 - EnooSoft': 'एक अच्छा दिन - enoosoft',
'Text Builder - Keyword suggestion for this app': 'टेक्स्ट बिल्डर - इस ऐप के लिए कीवर्ड सुझाव',
'Please make a "Keyword" that works like this': 'कृपया एक "कीवर्ड" बनाएं जो इस तरह काम करता है',
'Keyword suggestion': 'कीवर्ड सुझाव',
'Returns the date added the number': 'रिटर्न दिनांक संख्या जोड़ा गया',
},
'pt': {
'About': 'Cerca de',
'Text Builder': 'Construtor de texto',
'Input text here': 'Texto de entrada aqui',
'Copy': 'cópia de',
'Clear': 'Claro',
'Source text copied': 'Texto de origem copiado',
'Source text': 'Texto original',
'Result text copied': 'Texto de resultado copiado',
'Text will be converted here': 'O texto será convertido aqui',
'Result text': 'Texto de resultado',
'refer_to_the_usage_using_sample_text': 'Consulte o uso usando texto de amostra',
'todays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'A data de hoje será substituída por YYYMAMDD. por exemplo. 20210713.',
'yesterdays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'A data de ontem será substituída por YYYMAMDD. por exemplo. 20210713.',
'View Sample': 'Ver amostra',
'Convert to uppercase': 'Converter para maiúsculas',
'Convert to lowercase': 'Converter para minúsculas',
'Convert grid to insert sql': 'Converter grade para inserir SQL',
'Replace keywords to value': 'Substituir palavras-chave ao valor',
'years': 'anos',
'months': 'meses',
'days': 'dias',
'Replace to d-days from given date to today': 'Substitua para D-Day a partir da data de hoje',
'Replace to d-days between two given date': 'Substitua os dias entre duas datas',
'Replace to years-months-days from given date to today': 'Substituir aos anos-meses-dias a partir da data de hoje',
'Replace to days from given date to today': 'Substituir os dias a partir da data de hoje',
'Replace to days between two given date': 'Substitua os dias entre duas datas',
'Clear All': 'Limpar tudo',
'Clear Line': 'Linha clara',
'Flutter App by EnooSoft': 'App flutter por enoosoft',
'Date and time now': 'Data e hora agora',
'Source text must be at least 2 lines': 'O texto de origem deve ter pelo menos 2 linhas',
'Current Year (2 digits)': 'Ano atual (2 dígitos)',
'Current Month (2 digits)': 'Mês atual (2 dígitos)',
'Current Date (2 digits)': 'Data atual (2 dígitos)',
'Current Hour (24 Hours)': 'Hora atual (24 horas)',
'Current minutes': 'Minutos atuais.',
'Current seconds': 'Segundos atuais',
'Keyword': 'Palavra-chave',
'Filter': 'Filtro',
'Select Keyword': 'Selecione a palavra-chave.',
'Please select the keyword from the list': 'Por favor, selecione a palavra-chave da lista',
'Cancel': 'Cancelar',
'Confirm': 'confirme',
'Select': 'Selecione.',
'play store app title': 'Construtor de texto - Crie mensagens com várias palavras-chave e filtros',
'check this app detail': 'Marque este aplicativo: "Construtor de texto - Crie mensagens com várias palavras-chave e filtros',
'Share App': 'Compartilhe o aplicativo',
'😊Have a nice day🎉 - EnooSoft': '😊 Tome um bom dia - enoosoft',
'Text Builder - Keyword suggestion for this app': 'Construtor de texto - sugestão de palavra-chave para este aplicativo',
'Please make a "Keyword" that works like this': 'Por favor, faça uma "palavra-chave" que funciona como esta',
'Keyword suggestion': 'Sugestão de palavra-chave.',
'Returns the date added the number': 'Retorna a data adicionada o número',
},
'zh': {
'About': '关于',
'Text Builder': '文本建设者',
'Input text here': '在此输入文本',
'Copy': '复制',
'Clear': '清除',
'Source text copied': '源文本已复制',
'Source text': '源文本',
'Result text copied': '结果文本复制',
'Text will be converted here': '文本将在此转换',
'Result text': '结果文本',
'refer_to_the_usage_using_sample_text': '使用示例文本参考用法',
'todays_date_will_be_replaced_with_yyymmdd_eg_20210713': '今天的日期将被Yyymmdd替换。例如。 20210713.',
'yesterdays_date_will_be_replaced_with_yyymmdd_eg_20210713': '昨天的日期将被Yyymmdd替换。例如。 20210713.',
'View Sample': '查看样本',
'Convert to uppercase': '转换为大写',
'Convert to lowercase': '转换为小写',
'Convert grid to insert sql': '转换网格以插入SQL',
'Replace keywords to value': '将关键字替换为值',
'years': '年',
'months': '几个月',
'days': '天',
'Replace to d-days from given date to today': '从给定日期替换为今天的D日',
'Replace to d-days between two given date': '在两个给定日期之间更换日期',
'Replace to years-months-days from given date to today': '从给定日期替换为今天的日期',
'Replace to days from given date to today': '从给定日期替换到今天',
'Replace to days between two given date': '在两个给定日期之间更换日期',
'Clear All': '清除所有',
'Clear Line': '清除线',
'Flutter App by EnooSoft': 'Enoosoft的浮动应用程序',
'Date and time now': '日期和时间现在',
'Source text must be at least 2 lines': '源文本必须至少为2行',
'Current Year (2 digits)': '当年（2位数）',
'Current Month (2 digits)': '当月（2位数）',
'Current Date (2 digits)': '当前日期（2位数）',
'Current Hour (24 Hours)': '当前小时（24小时）',
'Current minutes': '当前纪要',
'Current seconds': '当前秒',
'Keyword': '关键词',
'Filter': '筛选',
'Select Keyword': '选择关键字',
'Please select the keyword from the list': '请从列表中选择关键字',
'Cancel': '取消',
'Confirm': '确认',
'Select': '选择',
'play store app title': '文本构建器 - 使用各种关键字和过滤器创建邮件',
'check this app detail': '选中此应用程序：“文本构建器 - 使用各种关键字和过滤器创建消息',
'Share App': '分享应用程序',
'😊Have a nice day🎉 - EnooSoft': '😊一个美好的一天 -  enoosoft',
'Text Builder - Keyword suggestion for this app': 'Text Builder  - 此应用程序的关键字建议',
'Please make a "Keyword" that works like this': '请制作一个“关键词”，它如下所示',
'Keyword suggestion': '关键词建议',
'Returns the date added the number': '返回日期添加了数字',
},
'ja': {
'About': '約',
'Text Builder': 'テキストビルダー',
'Input text here': 'ここに入力されたテキスト',
'Copy': 'コピー',
'Clear': '晴れ',
'Source text copied': 'ソーステキストがコピーされました',
'Source text': 'ソーステキスト',
'Result text copied': '結果テキストがコピーされました',
'Text will be converted here': 'テキストはここに変換されます',
'Result text': '結果テキスト',
'refer_to_the_usage_using_sample_text': 'サンプルテキストを使用した使用法を参照してください',
'todays_date_will_be_replaced_with_yyymmdd_eg_20210713': '今日の日付はyyymmddに置き換えられます。例えば。 20210713',
'yesterdays_date_will_be_replaced_with_yyymmdd_eg_20210713': '昨日の日付はyyymmddに置き換えられます。例えば。 20210713',
'View Sample': 'サンプルを見る',
'Convert to uppercase': '大文字に変換します',
'Convert to lowercase': '小文字に変換します',
'Convert grid to insert sql': 'グリッドを変換してSQLを挿入します',
'Replace keywords to value': 'キーワードを値に置き換えます',
'years': '年',
'months': '月',
'days': '日々',
'Replace to d-days from given date to today': '与えられた日付から今日までのD日に置き換える',
'Replace to d-days between two given date': '与えられた2日の間の日数に置き換えます',
'Replace to years-months-days from given date to today': '与えられた日から今日までの数年の日に置き換える',
'Replace to days from given date to today': '与えられた日付から今日までの日に置き換えます',
'Replace to days between two given date': '与えられた2日の間の日数に置き換えます',
'Clear All': 'すべてクリア',
'Clear Line': '明確な線',
'Flutter App by EnooSoft': 'Enoosoftによるフラッタアプリ',
'Date and time now': '今日の日時',
'Source text must be at least 2 lines': 'ソーステキストは少なくとも2行でなければなりません',
'Current Year (2 digits)': '現在の年（2桁）',
'Current Month (2 digits)': '現在の月（2桁）',
'Current Date (2 digits)': '現在の日付（2桁）',
'Current Hour (24 Hours)': '現在の時間（24時間）',
'Current minutes': '現在の分',
'Current seconds': '現在の秒数',
'Keyword': 'キーワード',
'Filter': 'フィルター',
'Select Keyword': 'キーワードを選択してください',
'Please select the keyword from the list': 'リストからキーワードを選択してください',
'Cancel': 'キャンセル',
'Confirm': '確認',
'Select': '選択する',
'play store app title': 'Text Builder  - さまざまなキーワードとフィルタのメッセージを作成する',
'check this app detail': 'このアプリをチェックしてください。 "Text Builder  - さまざまなキーワードやフィルタのメッセージを作成する',
'Share App': 'アプリを共有する',
'😊Have a nice day🎉 - EnooSoft': 'いいね。 -  Enoosoft.',
'Text Builder - Keyword suggestion for this app': 'Text Builder  - このアプリのキーワード提案',
'Please make a "Keyword" that works like this': 'このように動作する「キーワード」を作ってください',
'Keyword suggestion': 'キーワード提案',
'Returns the date added the number': '番号を追加した日付を返します',
},
'ru': {
'About': 'О',
'Text Builder': 'Строитель текста',
'Input text here': 'Вход текст здесь',
'Copy': 'Скопировать',
'Clear': 'Прозрачный',
'Source text copied': 'Исходный текст скопирован',
'Source text': 'Исходный текст',
'Result text copied': 'Результат текст скопирован',
'Text will be converted here': 'Текст будет преобразован здесь',
'Result text': 'Результат текст',
'refer_to_the_usage_using_sample_text': 'Обратитесь к использованию, используя образец текста',
'todays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'Сегодняшняя дата будет заменена на Yyymmdd. например. 20210713.',
'yesterdays_date_will_be_replaced_with_yyymmdd_eg_20210713': 'Вчерашняя дата будет заменена на Yyymmdd. например. 20210713.',
'View Sample': 'Просмотр образца',
'Convert to uppercase': 'Преобразовать в верхний регистр',
'Convert to lowercase': 'Преобразовать в нижний регистр',
'Convert grid to insert sql': 'Конвертировать сетку, чтобы вставить SQL',
'Replace keywords to value': 'Заменить ключевые слова на значение',
'years': 'годы',
'months': 'месяцы',
'days': 'дни',
'Replace to d-days from given date to today': 'Замените на D-Day с даты сегодня',
'Replace to d-days between two given date': 'Заменить на дни между двумя данными',
'Replace to years-months-days from given date to today': 'Заменить на годы месяцев с данной даты сегодня',
'Replace to days from given date to today': 'Заменить на дни с данной даты сегодня',
'Replace to days between two given date': 'Заменить на дни между двумя данными',
'Clear All': 'Очистить все',
'Clear Line': 'Прозрачная линия',
'Flutter App by EnooSoft': 'Работайте приложение по Enoosoft',
'Date and time now': 'Дата и время сейчас',
'Source text must be at least 2 lines': 'Исходный текст должен быть не менее 2 строк',
'Current Year (2 digits)': 'Текущий год (2 цифры)',
'Current Month (2 digits)': 'Текущий месяц (2 цифры)',
'Current Date (2 digits)': 'Текущая дата (2 цифры)',
'Current Hour (24 Hours)': 'Текущий час (24 часа)',
'Current minutes': 'Текущие минуты',
'Current seconds': 'Текущие секунды',
'Keyword': 'Ключевое слово',
'Filter': 'Фильтр',
'Select Keyword': 'Выберите ключевое слово',
'Please select the keyword from the list': 'Пожалуйста, выберите ключевое слово из списка',
'Cancel': 'Отмена',
'Confirm': 'Подтверждать',
'Select': 'Выбирать',
'play store app title': 'Text Builder - Создание сообщений с различными ключевыми словами и фильтрами',
'check this app detail': 'Проверьте это приложение: «Строитель текста - Создание сообщений с различными ключевыми словами и фильтрами',
'Share App': 'Поделиться приложением',
'😊Have a nice day🎉 - EnooSoft': '😊😊ave хороший день - Enoosoft',
'Text Builder - Keyword suggestion for this app': 'Text Builder - предложение ключевого слова для этого приложения',
'Please make a "Keyword" that works like this': 'Пожалуйста, сделайте «ключевое слово», которое работает так',
'Keyword suggestion': 'Предложение ключевых слов',
'Returns the date added the number': 'Возвращает дату добавления номера',
},
        };
      }
      