import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ko': {
'About': 'About',
'Astronomical calendar': '천문달력',
'Input text here': '텍스트를 입력하세요',
'Copy': '복사',
'Clear': '삭제',
'Cancel': '취소',
'Confirm': '확인',
'Select': '선택',
'app description': '천문현상을 볼 수 있는 달력입니다',
'Share App': '앱공유',
'😊Have a nice day🎉 - EnooSoft': '😊좋은 하루 보내세요🎉 - EnooSoft',
},
'en': {
'About': 'About',
'Astronomical calendar': 'Astronomical calendar',
'Input text here': 'Input text here',
'Copy': 'Copy',
'Clear': 'Clear',
'Cancel': 'Cancel',
'Confirm': 'Confirm',
'Select': 'Select',
'app description': 'Calendar to see astronomical phenomena.',
'Share App': 'Share App',
'😊Have a nice day🎉 - EnooSoft': '😊Have a nice day🎉 - EnooSoft',
},
'fr': {
'About': 'Sur',
'Astronomical calendar': 'Calendrier astronomique',
'Input text here': 'Texte d\'entrée ici',
'Copy': 'Copie',
'Clear': 'Dégager',
'Cancel': 'Annuler',
'Confirm': 'Confirmer',
'Select': 'Sélectionner',
'app description': 'Calendrier de voir des phénomènes astronomiques.',
'Share App': 'Partager l\'application',
'😊Have a nice day🎉 - EnooSoft': '😊Avoir une bonne journée🎉 - Enoosoft',
},
'es': {
'About': 'Sobre',
'Astronomical calendar': 'Calendario astronómico',
'Input text here': 'Texto de entrada aquí',
'Copy': 'Dupdo',
'Clear': 'Claro',
'Cancel': 'Cancelar',
'Confirm': 'Confirmar',
'Select': 'Seleccione',
'app description': 'Calendario para ver los fenómenos astronómicos.',
'Share App': 'Compartir aplicación',
'😊Have a nice day🎉 - EnooSoft': '😊Have un buen día🎉 - Enoosoft',
},
'de': {
'About': 'Über',
'Astronomical calendar': 'Astronomischer Kalender.',
'Input text here': 'Eingabestext hier.',
'Copy': 'Kopieren',
'Clear': 'Klar',
'Cancel': 'Abbrechen',
'Confirm': 'Bestätigen Sie',
'Select': 'Auswählen',
'app description': 'Kalender, um astronomische Phänomene zu sehen.',
'Share App': 'App teilen',
'😊Have a nice day🎉 - EnooSoft': '😊Habe ein schöner Tag - Enoosoft',
},
'hi': {
'About': 'के बारे में',
'Astronomical calendar': 'खगोलीय कैलेंडर',
'Input text here': 'इनपुट पाठ यहाँ',
'Copy': 'प्रतिलिपि',
'Clear': 'स्पष्ट',
'Cancel': 'रद्द करें',
'Confirm': 'पुष्टि करना',
'Select': 'चुनते हैं',
'app description': 'खगोलीय घटनाओं को देखने के लिए कैलेंडर।',
'Share App': 'ऐप शेयर करें',
'😊Have a nice day🎉 - EnooSoft': 'एक अच्छा दिन - enoosoft',
},
'pt': {
'About': 'Cerca de',
'Astronomical calendar': 'Calendário Astronômico.',
'Input text here': 'Texto de entrada aqui.',
'Copy': 'cópia de',
'Clear': 'Claro',
'Cancel': 'Cancelar',
'Confirm': 'confirme',
'Select': 'Selecione.',
'app description': 'Calendário para ver fenômenos astronômicos.',
'Share App': 'Compartilhe o aplicativo',
'😊Have a nice day🎉 - EnooSoft': '😊 Tome um bom dia - enoosoft',
},
'zh': {
'About': '关于',
'Astronomical calendar': '天文日历',
'Input text here': '在此输入文本',
'Copy': '复制',
'Clear': '清除',
'Cancel': '取消',
'Confirm': '确认',
'Select': '选择',
'app description': '日历看到天文现象。',
'Share App': '分享应用程序',
'😊Have a nice day🎉 - EnooSoft': '😊一个美好的一天 -  enoosoft',
},
'ja': {
'About': 'だいたい',
'Astronomical calendar': '天文カレンダー',
'Input text here': 'ここに入力されたテキスト',
'Copy': 'コピー',
'Clear': 'クリア',
'Cancel': 'キャンセル',
'Confirm': '確認',
'Select': '選択する',
'app description': '天文学的現象を見るためのカレンダー。',
'Share App': 'アプリを共有する',
'😊Have a nice day🎉 - EnooSoft': 'いいね。 -  Enoosoft.',
},
'ru': {
'About': 'О',
'Astronomical calendar': 'Астрономический календарь',
'Input text here': 'Вход текст здесь',
'Copy': 'Скопировать',
'Clear': 'Прозрачный',
'Cancel': 'Отмена',
'Confirm': 'Подтверждать',
'Select': 'Выбирать',
'app description': 'Календарь, чтобы увидеть астрономические явления.',
'Share App': 'Поделиться приложением',
'😊Have a nice day🎉 - EnooSoft': '😊😊ave хороший день - Enoosoft',
},
        };
      }
      